### ISSUE TITLE
_dbaid_maintenance_history not updated

### ISSUE THREAD

**Issue by chanchan126** [dc-sql/DBAid#10]
hi,
after doing the upgrade from previous verisons to 5.1.0, i noticed that the _dbaid_maintenance_history job is not updated with the latest parameters in the job step. this gives me error when running the job. also, the new step (deletion of log files) is not included.

can you check on this? 

cheers,
christian

**Comment by chanchan126** [comment]
old version
exec [_dbaid].[maintenance].[cleanup_history] @RetainDaysJob=92,@RetainDaysBackup=92,@RetainDaysCmdlog=92

new version
 exec [_dbaid].[maintenance].[cleanup_history] @job_olderthan_day=92, @backup_olderthan_day=92, @cmdlog_olderthan_day=92, @dbmail_olderthan_day=92, @maintplan_olderthan_day=92;

new job step: cleanup logs

**Comment by lukecl** [comment]
Yep, that is an issue
For now just manually re-create the job. this is specific to older versions.
