### ISSUE TITLE
Release fails when clients default language is not us_english

### ISSUE THREAD

**Issue by dc-sql** [dc-sql/DBAid#19]
If you get this error message your client language may not be set to us_english:

_Msg 15279, Level 16, State 1, Procedure sp_addmessage, Line 97
You must add the us_english version of this message before you can add the 'British' version.
** An error was encountered during execution of batch. Exiting._ 

To check what your client language is execute: 
select @@language 

To workaround this issue, add the following line at the beginning of the script:
SET LANGUAGE us_english;

**Comment by Teutenberg** [comment]
fork version [Teutenberg/DBAid] doesn't have this bug.
