### ISSUE TITLE
Use of deprecated views

### ISSUE THREAD

**Issue by thecosmictrickster** [dc-sql/DBAid#6]
The sys.sysconfigures view is being used in the script to create the dbaid database. This should be replaced with sys.configurations.

**Comment by Teutenberg** [comment]
Can you provide more details, like file and line number?

**Comment by thecosmictrickster** [comment]
Release 5.1.0, dbaid_release_Create.sql

Lines 1304, 5284, 5285

**Comment by Teutenberg** [comment]
I do not find the deprecated view "sys.sysconfigures" being used. 

Line 1304 = "FROM [master].[sys].[configurations]"
Line 5284 = "    WHEN @BackupSoftware IS NULL AND EXISTS(SELECT \* FROM sys.configurations WHERE name = 'backup compression default' AND value_in_use = 1) THEN 'Y'"
Line 5285 = "    WHEN @BackupSoftware IS NULL AND NOT EXISTS(SELECT \* FROM sys.configurations WHERE name = 'backup compression default' AND value_in_use = 1) THEN 'N'"

**Comment by thecosmictrickster** [comment]
Oops, used wrong search term. I re-downloaded release 5.1.0 - you're right, it's not there. Must have been updated already (or the folder I've got labelled 5.1.0 is not actually 5.1.0 - someone else provided it). Sorry for wasting your time there.
