### ISSUE TITLE
System index optimise job does practically nothing

### ISSUE THREAD

**Issue by thecosmictrickster** [dc-sql/DBAid#69]
The default configuration of the [_dbaid_index_optimise_system] SQL Agent job doesn't actually do much because it needs to have the @MSShippedObjects = 'Y' added to it. This parameter defaults to N and dictates whether items that ship with SQL Server (i.e., system objects) are processed or left alone.

**Comment by dcsql** [comment]
Fixing this.

**Comment by thecosmictrickster** [comment]
Fixed, release 6.4.8 created.
