### ISSUE TITLE
Deprecated Stored Proc sp_addrolemember

### ISSUE THREAD

**Issue by andythedba** [dc-sql/DBAid#71]
MS is deprecating sp_addrolemember at some point after SQL 2022. This is used twice in the dbaid_release_Create.sql script. The SP should be replaced with ALTER ROLE commands as suggested below.

--EXEC sp_addrolemember 'admin', '$(CollectorServiceAccount)';
--EXEC sp_addrolemember 'monitor', '$(CheckServiceAccount)';
ALTER ROLE [admin] ADD MEMBER [$(CollectorServiceAccount)];
ALTER ROLE [monitor] ADD MEMBER [$(CheckServiceAccount)];
GO

**Comment by thecosmictrickster** [comment]
Agreed. This was probably left behind when we were still supporting older versions of SQL Server and never got revisited.

**Comment by thecosmictrickster** [comment]
Fixed. See release 6.4.9.

**Comment by andythedba** [comment]
Thanks 😊
